apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
  labels:
    app: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring
        image: miksveg/monitoring-flask-app:latest
        ports:
        - containerPort: 5000
